### ISSUE TITLE
godot 4 port

### ISSUE THREAD

**Issue by elevchyt** [Dechode/Godot-Simple-Vehicle#2]
any plans on importing this to godot 4?
thank you!

**Comment by Dechode** [comment]
There is a godot4-port branch, which i did when godot 4 stable first came out. I have not tried it in a long time, but it should work with 4.x.

That being said, i am currently reworking this repo to be a "General purpose vehicle", which supports arbitrary amount of wheels, but does not have a real clutch or differentials like my "Advanced Vehicle" repo has. I have also switched from raycasts to shapecasts with cylinder shapes. Still needs a bit of work done before i push the changes.

**Comment by elevchyt** [comment]
Unfortunately, that one is done in C# (not gdscript), and I'm getting some errors importing it in Godot 4.21.

That's great to hear, I'll definitely keep an eye out in this repo for any changes!

**Comment by Dechode** [comment]
I did not mean the pull request for c# by michurebmann, but one of my own branches which is written in gdscript, here is a link: https://github.com/Dechode/Godot-Simple-Vehicle/tree/godot4-port

I just pushed the reworked project to a branch called general-purpose-vehicle, here is a link: https://github.com/Dechode/Godot-Simple-Vehicle/tree/general-purpose-vehicle

I recommend you try that instead of the old branch. It does use Godot-Jolt addon for physics engine so it's a little bit larger in size though.
Dont mind the dirtbike scene, it is not really working atm.

**Comment by elevchyt** [comment]
Apologies, thank you very much, I'm going to have a look!

**Comment by Dechode** [comment]
If you already checked it out, there was a bug with spring length calculations, but i just pushed a fix for it. Fetch and pull the new commits to get a better experience. 

Also could you let me know if it is working like intended so i can close this issue?

**Comment by elevchyt** [comment]
Just checked it out, looks really good!

**Comment by Dechode** [comment]
Thanks! Glad it was helpful. I'll close this issue now
